Sign Up and Login
DDVVPP/GitNote pull request #12
Opened 2024-03-13 08:53 UTC by DDVVPP

2024-03-13 18:40 UTC, DDVVPP commented on components/BasicAuthLogin.tsx
> +  const handleSubmit = async () => {
Do I need to add a try/catch here?

2024-03-13 18:40 UTC, DDVVPP commented on components/ProviderLogins.tsx
> +const submit = async (formData: FormData) => {
Do I need to add a try/catch here?

2024-03-13 18:40 UTC, DDVVPP commented on components/onboarding/CreateAccount.tsx
> +  const submit = () => {
Do I need a try/catch here?

2024-03-13 20:05 UTC, brandonetter requested changes
Those are the big things I see. If you wanted to expand on that to use a "toast" for notifications when there's a register failure try 
```
npm i react-hot-toast
```

Then add the Toaster to your `layout.tsx`
```js
// layout.tsx
import { Toaster } from "react-hot-toast";
...etc...
 return (
    <html lang="en">
      <body className={inter.className}>
        {children}
        <Toaster position="bottom-right" />
      </body>
    </html>
  );
```

You can then call 'toast' in your client components.

```js
// CreateAccount.tsx

  const submit = async () => {
    if (data) {
      const { user, error } = await createUser(data);
      if (error) {
        console.log(error);
        toast.error(error);
      } else {
        // the user is created, let's log them in and redirect to the onboarding page
        await signIn("credentials", {
          email: data.email,
          password: data.password,
          redirect: false,
        });
        redirect("/sign-up/onboarding");
      }
    }
  };
  ```
  
  
So with all the suggested changes we get:


https://github.com/DDVVPP/GitNote/assets/4108484/2003f0e6-a25d-47ab-b8e2-bffe126f2eb3


Vs Currently (let me know if we're out of sync again! This is how it behaves for me)


https://github.com/DDVVPP/GitNote/assets/4108484/0ed059ee-1a65-4b51-bf67-cd449e60060e

2024-03-13 20:05 UTC, brandonetter commented on components/BasicAuthLogin.tsx
> +          onChange={(event) => setPassword(event?.target.value)}
```suggestion
          label="Password"
          name="password"
          placeholder="Enter your password"
          value={password}
          type="password"
          onChange={(event) => setPassword(event?.target.value)}
```

Use this to hide the input's display

2024-03-13 20:05 UTC, brandonetter commented on components/onboarding/CreateAccount.tsx
> +          onChange={(event) =>
```suggestion
          label="Password"
          name="password"
          placeholder="Enter your password"
          value={data.password}
          type="password"
          onChange={(event) =>
```
Same here

2024-03-13 20:05 UTC, brandonetter commented on components/onboarding/CreateAccount.tsx
> +  const submit = () => {
Since your createUser could throw an error, yes. Or you could design your createUser function to just return some "error" message in an object and handle it here (maybe with a toast!)

2024-03-13 20:05 UTC, brandonetter commented on components/onboarding/CreateAccount.tsx
> +    });
```suggestion

```
You don't need to set the data to itself here.

2024-03-13 20:05 UTC, brandonetter commented on components/onboarding/CreateAccount.tsx
> +  };
Right now we're not actually logging in when we signup. We're just creating the user then redirecting. You have to actually call "signIn" for that. And in order for that to work we need to make sure we know the signUp was successful

```suggestion
  const submit = async () => { // make async so we can await promises
    if (data) {
      const { user, error } = await createUser(data); 
      if (error) {
        console.log(error);
        // we could display a toast here or some notification
      } else {
        // the user is created, let's log them in and redirect to the onboarding page
        await signIn("credentials", {
          email: data.email,
          password: data.password,
          redirect: false,
        });
        redirect("/sign-up/onboarding");
      }
    }
  };
```

To get this to work, In your user.actions you could return an error object along with the user to indicate success or failure:

```js
// user.actions.ts
export async function createUser(data: Partial<User>) {
  try {
    if (data) {
      const { password } = data;
      const hashedPassword = bcryptjs.hashSync(password as string, 10);

      const user = await prisma.user.create({
        data: {
          ...data,
          password: hashedPassword,
        },
      });
      return { user, error: null };
    }
  } catch (error) {
    console.error("Error creating user:", error);
    return { error: "An unexpected error occurred while creating user." };
  }
  return { error: "An unexpected error occurred while creating user." };
}
```


That way if there's an error with our DB, or if we for some reason don't get data, we still return an error. If we instead create the user we return the user but set error to "null"

2024-03-14 17:35 UTC, brandonetter requested changes

2024-03-14 17:35 UTC, brandonetter commented on components/BasicAuthLogin.tsx
> +    }
```
import { ZodError } from 'zod'
```

```suggestion
    try {
      const partialUserSchema = userSchema.partial();
      partialUserSchema.parse(data);
      const { email, password } = data;
      await credentialsSignIn({
        email,
        password
      });
    } catch (error) {
      if (error instanceof ZodError) {
        console.log("zodErrors", error);
        // these errors come from zod
        // show the user the messages in the form
      } else {
        // these errors come from invalid signIn
        // display your toast
        toast.error("nooo");
      }
      return;
    }
```

We can consolidate our error catching by using `instance of ZodError` to figure out where the error came from.


Example of the code working:

https://github.com/DDVVPP/GitNote/assets/4108484/6d431b83-0205-40fd-bf4e-6e1b7f733169

2024-03-14 17:35 UTC, brandonetter commented on components/onboarding/CreateAccount.tsx
> +  // const [zodErrors, setZodErrors] = useState({});
I see you were blocking this out. Let's implement them and then get this merged.

2024-03-14 17:50 UTC, merged